# Generated by Django 2.2.6 on 2019-10-23 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191021_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
