# Generated by Django 2.2.6 on 2019-10-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191029_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eye',
        ),
        migrations.AlterField(
            model_name='return_images',
            name='eye',
            field=models.ImageField(upload_to='output'),
        ),
        migrations.AlterField(
            model_name='return_images',
            name='eyebrow',
            field=models.ImageField(upload_to='output'),
        ),
        migrations.AlterField(
            model_name='return_images',
            name='face',
            field=models.ImageField(upload_to='output'),
        ),
        migrations.AlterField(
            model_name='return_images',
            name='mouse',
            field=models.ImageField(upload_to='output'),
        ),
        migrations.AlterField(
            model_name='return_images',
            name='nose',
            field=models.ImageField(upload_to='output'),
        ),
    ]
