# Generated by Django 2.2.6 on 2019-10-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191029_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
