# Generated by Django 2.2.6 on 2019-10-31 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191031_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eye',
        ),
        migrations.DeleteModel(
            name='Eye_Brow',
        ),
        migrations.DeleteModel(
            name='Mouse',
        ),
        migrations.DeleteModel(
            name='Nose',
        ),
    ]
