# Generated by Django 2.2.6 on 2019-10-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_eye_eye_brow_mouse_nose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eye',
        ),
        migrations.DeleteModel(
            name='Eye_Brow',
        ),
        migrations.DeleteModel(
            name='Mouse',
        ),
        migrations.DeleteModel(
            name='Nose',
        ),
    ]
