# Generated by Django 2.2.6 on 2019-10-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20191031_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('content', models.TextField(max_length=500)),
                ('urls', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eye_Brow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('content', models.TextField(max_length=500)),
                ('urls', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('content', models.TextField(max_length=500)),
                ('urls', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('content', models.TextField(max_length=500)),
                ('urls', models.TextField(max_length=100)),
            ],
        ),
    ]
