# Generated by Django 2.2.6 on 2019-10-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_eye_eye_brow_mouse_nose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eye',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='eye_brow',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='nose',
            name='urls',
        ),
    ]
