# Generated by Django 2.2.6 on 2019-10-31 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191031_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_image',
            name='create_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='return_images',
            name='create_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
