# Generated by Django 2.2.6 on 2019-10-31 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20191031_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_image',
            name='create_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='return_images',
            name='create_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
