# Generated by Django 2.2.6 on 2019-11-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20191101_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eye',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('positive', models.TextField(max_length=500)),
                ('negative', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Eye_Brow',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('positive', models.TextField(max_length=500)),
                ('negative', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('positive', models.TextField(max_length=500)),
                ('negative', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Nose',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('positive', models.TextField(max_length=500)),
                ('negative', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Eye_Brow_negative',
        ),
        migrations.DeleteModel(
            name='Eye_Brow_positive',
        ),
        migrations.DeleteModel(
            name='Eye_negative',
        ),
        migrations.DeleteModel(
            name='Eye_positive',
        ),
        migrations.DeleteModel(
            name='Mouse_negative',
        ),
        migrations.DeleteModel(
            name='Mouse_positive',
        ),
        migrations.DeleteModel(
            name='Nose_negative',
        ),
        migrations.DeleteModel(
            name='Nose_positive',
        ),
    ]
