# Generated by Django 2.2.6 on 2019-11-01 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20191101_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('dir', models.TextField(max_length=255)),
                ('create_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='Input_Image',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='eye',
            name='negative',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eye',
            name='positive',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eye_brow',
            name='negative',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eye_brow',
            name='positive',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='negative',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='positive',
            field=models.TextField(max_length=255),
        ),
    ]
