# Generated by Django 2.2.6 on 2019-11-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20191101_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Path',
            new_name='Image',
        ),
        migrations.DeleteModel(
            name='Return_Images',
        ),
    ]
